package com.ryccoatika.journeyrecorder.ui.theme

import androidx.compose.ui.graphics.Color

// Clean pro-tool palette: indigo primary, red reserved for recording states
// (the M3 error slot doubles as the "recording" accent), amber tertiary for
// RECOVERED/warning badges.

// Light
val IndigoPrimary = Color(0xFF4355B9)
val IndigoOnPrimary = Color(0xFFFFFFFF)
val IndigoPrimaryContainer = Color(0xFFDEE0FF)
val IndigoOnPrimaryContainer = Color(0xFF00105C)
val SlateSecondary = Color(0xFF5B5D72)
val SlateOnSecondary = Color(0xFFFFFFFF)
val SlateSecondaryContainer = Color(0xFFE0E1F9)
val SlateOnSecondaryContainer = Color(0xFF181A2C)
val AmberTertiary = Color(0xFF7C5800)
val AmberOnTertiary = Color(0xFFFFFFFF)
val AmberTertiaryContainer = Color(0xFFFFDEA6)
val AmberOnTertiaryContainer = Color(0xFF271900)
val RecordRed = Color(0xFFBA1A1A)
val RecordOnRed = Color(0xFFFFFFFF)
val RecordRedContainer = Color(0xFFFFDAD6)
val RecordOnRedContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFAF8FF)
val LightOnBackground = Color(0xFF1A1B21)
val LightSurface = Color(0xFFFAF8FF)
val LightOnSurface = Color(0xFF1A1B21)
val LightSurfaceVariant = Color(0xFFE2E1EC)
val LightOnSurfaceVariant = Color(0xFF45464F)
val LightOutline = Color(0xFF767680)
val LightOutlineVariant = Color(0xFFC6C5D0)
val LightSurfaceContainer = Color(0xFFEEEDF7)
val LightSurfaceContainerHigh = Color(0xFFE8E7F1)
val LightSurfaceContainerHighest = Color(0xFFE2E1EC)
val LightSurfaceContainerLow = Color(0xFFF4F2FC)

// Dark
val DarkIndigoPrimary = Color(0xFFBAC3FF)
val DarkIndigoOnPrimary = Color(0xFF08218A)
val DarkIndigoPrimaryContainer = Color(0xFF293CA0)
val DarkIndigoOnPrimaryContainer = Color(0xFFDEE0FF)
val DarkSlateSecondary = Color(0xFFC4C5DD)
val DarkSlateOnSecondary = Color(0xFF2D2F42)
val DarkSlateSecondaryContainer = Color(0xFF434559)
val DarkSlateOnSecondaryContainer = Color(0xFFE0E1F9)
val DarkAmberTertiary = Color(0xFFF7BD48)
val DarkAmberOnTertiary = Color(0xFF412D00)
val DarkAmberTertiaryContainer = Color(0xFF5E4200)
val DarkAmberOnTertiaryContainer = Color(0xFFFFDEA6)
val DarkRecordRed = Color(0xFFFFB4AB)
val DarkRecordOnRed = Color(0xFF690005)
val DarkRecordRedContainer = Color(0xFF93000A)
val DarkRecordOnRedContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF121318)
val DarkOnBackground = Color(0xFFE3E1E9)
val DarkSurface = Color(0xFF121318)
val DarkOnSurface = Color(0xFFE3E1E9)
val DarkSurfaceVariant = Color(0xFF45464F)
val DarkOnSurfaceVariant = Color(0xFFC6C5D0)
val DarkOutline = Color(0xFF90909A)
val DarkOutlineVariant = Color(0xFF45464F)
val DarkSurfaceContainer = Color(0xFF1E1F25)
val DarkSurfaceContainerHigh = Color(0xFF292A2F)
val DarkSurfaceContainerHighest = Color(0xFF34343A)
val DarkSurfaceContainerLow = Color(0xFF1A1B21)
