package com.ryccoatika.journeyrecorder.export

import com.ryccoatika.journeyrecorder.data.db.Confidence
import com.ryccoatika.journeyrecorder.data.db.EventType
import com.ryccoatika.journeyrecorder.data.db.JourneyEntity
import com.ryccoatika.journeyrecorder.data.db.JourneyEventEntity
import com.ryccoatika.journeyrecorder.data.db.JourneyStatus
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import java.util.TimeZone

class MarkdownGeneratorTest {
    // 2026-01-15 10:30:00 UTC
    private val t0 = 1_768_473_000_000L

    private lateinit var originalTimeZone: TimeZone

    @Before
    fun setUp() {
        originalTimeZone = TimeZone.getDefault()
        TimeZone.setDefault(TimeZone.getTimeZone("UTC"))
    }

    @After
    fun tearDown() {
        TimeZone.setDefault(originalTimeZone)
    }

    private fun journey(
        name: String = "Checkout Flow",
        appVersionName: String? = "2.1.0",
        status: JourneyStatus = JourneyStatus.COMPLETED,
        noElementIds: Boolean = false,
        endedAt: Long? = t0 + 60_000L,
    ) = JourneyEntity(
        id = 1L,
        name = name,
        targetPackage = "com.example.shop",
        targetAppLabel = "Shop",
        appVersionName = appVersionName,
        deviceInfo = "Google Pixel 8",
        androidVersion = "15 (API 35)",
        startedAt = t0,
        endedAt = endedAt,
        status = status,
        noElementIds = noElementIds,
    )

    private fun event(
        sequence: Int,
        eventType: EventType,
        wallClockMs: Long = t0 + sequence * 1000L,
        screenName: String? = null,
        elementId: String? = null,
        elementText: String? = null,
        contentDesc: String? = null,
        className: String? = null,
        bounds: String? = null,
        typedText: String? = null,
        masked: Boolean = false,
        confidence: Confidence = Confidence.NORMAL,
        collectionIndex: Int? = null,
    ) = JourneyEventEntity(
        id = sequence + 1L,
        journeyId = 1L,
        sequence = sequence,
        wallClockMs = wallClockMs,
        eventType = eventType,
        screenName = screenName,
        elementId = elementId,
        elementText = elementText,
        contentDesc = contentDesc,
        className = className,
        bounds = bounds,
        typedText = typedText,
        masked = masked,
        confidence = confidence,
        collectionIndex = collectionIndex,
    )

    @Test
    fun `empty journey renders header and footer only`() {
        val actual = MarkdownGenerator.generate(journey(), emptyList())

        val expected = """
            # Journey: Checkout Flow

            | | |
            |---|---|
            | App | `com.example.shop` v2.1.0 (Shop) |
            | Device | Google Pixel 8 |
            | Android | 15 (API 35) |
            | Recorded | 2026-01-15 10:30 (60s) |
            | Total steps | 0 |

            _Generated by JourneyRecorder_
        """.trimIndent() + "\n"

        assertEquals(expected, actual)
    }

    @Test
    fun `multi-screen grouping with continuous numbering`() {
        val events = listOf(
            event(0, EventType.CLICK, elementText = "Start"),
            event(1, EventType.SCREEN_OPEN, screenName = "LoginActivity"),
            event(
                2,
                EventType.CLICK,
                screenName = "LoginActivity",
                elementText = "Sign In",
                elementId = "com.foo:id/btn_login",
                contentDesc = "Sign in button",
                bounds = "[120,840][960,984]",
            ),
            event(3, EventType.SCREEN_OPEN, screenName = "HomeActivity"),
            event(
                4,
                EventType.CLICK,
                screenName = "HomeActivity",
                contentDesc = "Menu",
                className = "android.widget.ImageButton",
            ),
        )

        // Passed in reverse to prove defensive sorting by sequence.
        val actual = MarkdownGenerator.generate(journey(), events.reversed())

        val expected = """
            # Journey: Checkout Flow

            | | |
            |---|---|
            | App | `com.example.shop` v2.1.0 (Shop) |
            | Device | Google Pixel 8 |
            | Android | 15 (API 35) |
            | Recorded | 2026-01-15 10:30 (60s) |
            | Total steps | 5 |

            ## Steps

            ### Screen: (initial)

            1. **Tap** "Start"

            ### Screen: LoginActivity

            2. **Open screen** `LoginActivity`
            3. **Tap** "Sign In" — id: `com.foo:id/btn_login`, content-desc: "Sign in button", bounds: `[120,840][960,984]`

            ### Screen: HomeActivity

            4. **Open screen** `HomeActivity`
            5. **Tap** "Menu" (content-desc)

            _Generated by JourneyRecorder_
        """.trimIndent() + "\n"

        assertEquals(expected, actual)
    }

    @Test
    fun `masked text input and clear text steps`() {
        val events = listOf(
            event(
                0,
                EventType.TEXT_INPUT,
                screenName = "LoginActivity",
                elementText = "Email",
                elementId = "com.foo:id/email",
                typedText = "qa@test.com",
            ),
            event(
                1,
                EventType.TEXT_INPUT,
                elementText = "Password",
                elementId = "com.foo:id/password",
                typedText = null,
                masked = true,
            ),
            event(
                2,
                EventType.TEXT_INPUT,
                elementText = "Search",
                typedText = "",
            ),
        )

        val actual = MarkdownGenerator.generate(journey(), events)

        val expected = """
            # Journey: Checkout Flow

            | | |
            |---|---|
            | App | `com.example.shop` v2.1.0 (Shop) |
            | Device | Google Pixel 8 |
            | Android | 15 (API 35) |
            | Recorded | 2026-01-15 10:30 (60s) |
            | Total steps | 3 |

            ## Steps

            ### Screen: LoginActivity

            1. **Type** "qa@test.com" into "Email" — id: `com.foo:id/email`
            2. **Type** `<masked sensitive value>` into "Password" — id: `com.foo:id/password` (masked)
            3. **Clear text** in "Search"

            _Generated by JourneyRecorder_
        """.trimIndent() + "\n"

        assertEquals(expected, actual)
    }

    @Test
    fun `markdown special characters are escaped in dynamic text`() {
        val events = listOf(
            event(
                0,
                EventType.CLICK,
                screenName = "Sale_Page",
                elementText = "Buy *now* | 50% `off`",
            ),
            event(
                1,
                EventType.CLICK,
                elementText = "Tap [here]",
                elementId = "com.foo:id/`weird`id",
            ),
        )

        val actual = MarkdownGenerator.generate(journey(name = "My_Journey *1*"), events)

        val expected = """
            # Journey: My\_Journey \*1\*

            | | |
            |---|---|
            | App | `com.example.shop` v2.1.0 (Shop) |
            | Device | Google Pixel 8 |
            | Android | 15 (API 35) |
            | Recorded | 2026-01-15 10:30 (60s) |
            | Total steps | 2 |

            ## Steps

            ### Screen: Sale\_Page

            1. **Tap** "Buy \*now\* \| 50% \`off\`"
            2. **Tap** "Tap \[here\]" — id: `com.foo:id/weirdid`

            _Generated by JourneyRecorder_
        """.trimIndent() + "\n"

        assertEquals(expected, actual)
    }

    @Test
    fun `pause marker inserted for gaps over five seconds`() {
        val events = listOf(
            event(0, EventType.CLICK, wallClockMs = t0, screenName = "Main", elementText = "First"),
            event(1, EventType.CLICK, wallClockMs = t0 + 6_400L, elementText = "Second"),
        )

        val actual = MarkdownGenerator.generate(journey(), events)

        val expected = """
            # Journey: Checkout Flow

            | | |
            |---|---|
            | App | `com.example.shop` v2.1.0 (Shop) |
            | Device | Google Pixel 8 |
            | Android | 15 (API 35) |
            | Recorded | 2026-01-15 10:30 (60s) |
            | Total steps | 2 |

            ## Steps

            ### Screen: Main

            1. **Tap** "First"

            _(pause ~6s)_

            2. **Tap** "Second"

            _Generated by JourneyRecorder_
        """.trimIndent() + "\n"

        assertEquals(expected, actual)
    }

    @Test
    fun `low confidence, collection index, system dialog and app marker rendering`() {
        val events = listOf(
            event(
                0,
                EventType.CLICK,
                screenName = "Checkout",
                className = "android.widget.Button",
                bounds = "[0,0][100,100]",
                confidence = Confidence.LOW,
                collectionIndex = 3,
            ),
            event(
                1,
                EventType.SCROLL,
                className = "androidx.recyclerview.widget.RecyclerView",
            ),
            event(
                2,
                EventType.SYSTEM_DIALOG,
                elementText = "Tapped Allow on permission dialog",
            ),
            event(3, EventType.SYSTEM_DIALOG),
            event(
                4,
                EventType.APP_MARKER,
                elementText = "Left target app (com.example.shop)",
            ),
        )

        val actual = MarkdownGenerator.generate(journey(), events)

        val expected = """
            # Journey: Checkout Flow

            | | |
            |---|---|
            | App | `com.example.shop` v2.1.0 (Shop) |
            | Device | Google Pixel 8 |
            | Android | 15 (API 35) |
            | Recorded | 2026-01-15 10:30 (60s) |
            | Total steps | 5 |

            ## Steps

            ### Screen: Checkout

            1. **Tap** Button — bounds: `[0,0][100,100]`, item #3 (low confidence)
            2. **Scroll** in RecyclerView
            3. **System**: Tapped Allow on permission dialog
            4. **System**: interacted with system dialog
            5. _Left target app (com.example.shop)_

            _Generated by JourneyRecorder_
        """.trimIndent() + "\n"

        assertEquals(expected, actual)
    }

    @Test
    fun `recovered status and missing element ids render notes`() {
        val actual = MarkdownGenerator.generate(
            journey(
                appVersionName = null,
                status = JourneyStatus.RECOVERED,
                noElementIds = true,
                endedAt = null,
            ),
            emptyList(),
        )

        val expected = """
            # Journey: Checkout Flow

            | | |
            |---|---|
            | App | `com.example.shop` vunknown (Shop) |
            | Device | Google Pixel 8 |
            | Android | 15 (API 35) |
            | Recorded | 2026-01-15 10:30 |
            | Total steps | 0 |

            > **Warning:** Recording ended unexpectedly; journey may be incomplete.

            > **Note:** Target app exposes no element IDs — steps use text/bounds locators.

            _Generated by JourneyRecorder_
        """.trimIndent() + "\n"

        assertEquals(expected, actual)
    }
}
