package com.ryccoatika.journeyrecorder.export

import com.ryccoatika.journeyrecorder.data.db.Confidence
import com.ryccoatika.journeyrecorder.data.db.EventType
import com.ryccoatika.journeyrecorder.data.db.JourneyEntity
import com.ryccoatika.journeyrecorder.data.db.JourneyEventEntity
import com.ryccoatika.journeyrecorder.data.db.JourneyStatus
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.math.roundToLong

/**
 * Pure (journey, events) -> markdown renderer. No Android dependencies so it is
 * fully testable on the JVM. Dates are formatted with Locale.US and the default
 * timezone (tests pin the timezone for stable golden strings).
 */
object MarkdownGenerator {

    private const val PAUSE_THRESHOLD_MS = 5000L

    fun generate(journey: JourneyEntity, events: List<JourneyEventEntity>): String {
        // Events arrive pre-sorted by sequence; sort defensively anyway.
        val sorted = events.sortedBy { it.sequence }
        val sb = StringBuilder()
        appendHeader(sb, journey, sorted.size)
        if (sorted.isNotEmpty()) {
            appendSteps(sb, sorted)
        }
        sb.appendLine()
        sb.appendLine("_Generated by JourneyRecorder_")
        return sb.toString()
    }

    private fun appendHeader(sb: StringBuilder, journey: JourneyEntity, eventCount: Int) {
        sb.appendLine("# Journey: ${escapeMd(journey.name)}")
        sb.appendLine()
        sb.appendLine("| | |")
        sb.appendLine("|---|---|")

        val version = journey.appVersionName?.takeIf { it.isNotBlank() } ?: "unknown"
        val label = journey.targetAppLabel?.takeIf { it.isNotBlank() }
        val appCell = buildString {
            append('`').append(stripBackticks(journey.targetPackage)).append('`')
            append(" v").append(escapeMd(version))
            if (label != null) {
                append(" (").append(escapeMd(label)).append(')')
            }
        }
        sb.appendLine("| App | $appCell |")
        sb.appendLine("| Device | ${escapeMd(journey.deviceInfo)} |")
        sb.appendLine("| Android | ${escapeMd(journey.androidVersion)} |")

        val formatter = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.US)
        val recordedCell = buildString {
            append(formatter.format(Date(journey.startedAt)))
            val endedAt = journey.endedAt
            if (endedAt != null) {
                val durationSeconds = ((endedAt - journey.startedAt) / 1000.0).roundToLong()
                append(" (").append(durationSeconds).append("s)")
            }
        }
        sb.appendLine("| Recorded | $recordedCell |")
        sb.appendLine("| Total steps | $eventCount |")

        if (journey.status == JourneyStatus.RECOVERED) {
            sb.appendLine()
            sb.appendLine("> **Warning:** Recording ended unexpectedly; journey may be incomplete.")
        }
        if (journey.noElementIds) {
            sb.appendLine()
            sb.appendLine("> **Note:** Target app exposes no element IDs — steps use text/bounds locators.")
        }
    }

    private fun appendSteps(sb: StringBuilder, sorted: List<JourneyEventEntity>) {
        sb.appendLine()
        sb.appendLine("## Steps")
        var currentScreenLabel: String? = null
        var previous: JourneyEventEntity? = null
        sorted.forEachIndexed { index, event ->
            var pauseEmitted = false
            val prev = previous
            if (prev != null) {
                val gapMs = event.wallClockMs - prev.wallClockMs
                if (gapMs > PAUSE_THRESHOLD_MS) {
                    val pauseSeconds = (gapMs / 1000.0).roundToLong()
                    sb.appendLine()
                    sb.appendLine("_(pause ~${pauseSeconds}s)_")
                    pauseEmitted = true
                }
            }
            // A null screenName carries the current section forward; before any
            // screen has been seen it falls into the "(initial)" section.
            val label = event.screenName?.takeIf { it.isNotBlank() }
                ?: currentScreenLabel
                ?: "(initial)"
            if (label != currentScreenLabel) {
                sb.appendLine()
                sb.appendLine("### Screen: ${escapeMd(label)}")
                sb.appendLine()
                currentScreenLabel = label
            } else if (pauseEmitted) {
                sb.appendLine()
            }
            sb.appendLine("${index + 1}. ${renderEvent(event)}")
            previous = event
        }
    }

    private fun renderEvent(event: JourneyEventEntity): String = when (event.eventType) {
        EventType.SCREEN_OPEN -> {
            // Dialog rows reuse SCREEN_OPEN with the message in elementText and
            // the screenName unchanged (dialogs are not screen boundaries).
            val dialog = event.elementText?.takeIf { it.isNotBlank() }
            if (dialog != null) {
                "**${escapeMd(dialog)}**" + lowConfidenceSuffix(event)
            } else {
                val name = event.screenName?.takeIf { it.isNotBlank() } ?: "unknown"
                "**Open screen** `${stripBackticks(name)}`" + lowConfidenceSuffix(event)
            }
        }
        EventType.CLICK -> renderAction("**Tap**", event)
        EventType.LONG_CLICK -> renderAction("**Long-press**", event)
        EventType.SELECT -> renderAction("**Select**", event)
        EventType.TEXT_INPUT -> renderTextInput(event)
        EventType.SCROLL -> renderScroll(event)
        EventType.SYSTEM_DIALOG -> {
            val text = event.elementText?.takeIf { it.isNotBlank() }
            val body = text?.let { escapeMd(it) } ?: "interacted with system dialog"
            "**System**: $body" + lowConfidenceSuffix(event)
        }
        EventType.APP_MARKER -> {
            val text = event.elementText?.takeIf { it.isNotBlank() } ?: "App marker"
            "_${escapeMd(text)}_" + lowConfidenceSuffix(event)
        }
    }

    private fun renderAction(verb: String, event: JourneyEventEntity): String {
        val (label, contentDescShown) = elementDescription(event)
        return "$verb $label${attributeTail(event, contentDescShown)}"
    }

    private fun renderTextInput(event: JourneyEventEntity): String {
        val (label, contentDescShown) = elementDescription(event)
        val tail = attributeTail(event, contentDescShown)
        return when {
            event.masked -> "**Type** `<masked sensitive value>` into $label$tail (masked)"
            event.typedText.isNullOrEmpty() -> "**Clear text** in $label$tail"
            else -> "**Type** \"${escapeMd(event.typedText)}\" into $label$tail"
        }
    }

    private fun renderScroll(event: JourneyEventEntity): String {
        // For scrolls, elementText carries a direction/range hint, so the target
        // description skips it and falls through to content-desc / class name.
        val hint = event.elementText?.takeIf { it.isNotBlank() }
        val contentDesc = event.contentDesc?.takeIf { it.isNotBlank() }
        val className = event.className?.takeIf { it.isNotBlank() }
        val target: String
        val contentDescShown: Boolean
        when {
            contentDesc != null -> {
                target = "\"${escapeMd(contentDesc)}\" (content-desc)"
                contentDescShown = true
            }
            className != null -> {
                target = escapeMd(className.substringAfterLast('.'))
                contentDescShown = false
            }
            else -> {
                target = "element"
                contentDescShown = false
            }
        }
        val prefix = hint?.let { escapeMd(it) } ?: "in"
        return "**Scroll** $prefix $target${attributeTail(event, contentDescShown)}"
    }

    /**
     * Precedence: elementText -> contentDesc -> simple class name -> "element".
     * Returns the label and whether the content description was used as the label.
     */
    private fun elementDescription(event: JourneyEventEntity): Pair<String, Boolean> {
        val text = event.elementText?.takeIf { it.isNotBlank() }
        val contentDesc = event.contentDesc?.takeIf { it.isNotBlank() }
        val className = event.className?.takeIf { it.isNotBlank() }
        return when {
            text != null -> "\"${escapeMd(text)}\"" to false
            contentDesc != null -> "\"${escapeMd(contentDesc)}\" (content-desc)" to true
            className != null -> escapeMd(className.substringAfterLast('.')) to false
            else -> "element" to false
        }
    }

    private fun attributeTail(event: JourneyEventEntity, contentDescShown: Boolean): String {
        val parts = mutableListOf<String>()
        event.elementId?.takeIf { it.isNotBlank() }?.let { parts += "id: `${stripBackticks(it)}`" }
        val contentDesc = event.contentDesc?.takeIf { it.isNotBlank() }
        if (contentDesc != null && !contentDescShown && contentDesc != event.elementText) {
            parts += "content-desc: \"${escapeMd(contentDesc)}\""
        }
        event.bounds?.takeIf { it.isNotBlank() }?.let { parts += "bounds: `${stripBackticks(it)}`" }
        event.collectionIndex?.let { parts += "item #$it" }
        val tail = if (parts.isEmpty()) "" else " — " + parts.joinToString(", ")
        return tail + lowConfidenceSuffix(event)
    }

    private fun lowConfidenceSuffix(event: JourneyEventEntity): String =
        if (event.confidence == Confidence.LOW) " (low confidence)" else ""

    /**
     * Escapes markdown control characters in dynamic text (not for code spans).
     * Newlines are collapsed so one event always renders as one list line —
     * multi-line text pasted in the target app must not inject fake headings
     * or steps into the export.
     */
    private fun escapeMd(value: String): String = buildString(value.length + 8) {
        var lastWasNewline = false
        for (c in value) {
            when (c) {
                '\n', '\r' -> {
                    if (!lastWasNewline) append(' ')
                    lastWasNewline = true
                    continue
                }
                '`', '|', '*', '_', '[', ']', '<', '>', '#' -> {
                    append('\\')
                    append(c)
                }
                else -> append(c)
            }
            lastWasNewline = false
        }
    }

    /** Values placed inside backtick code spans go in raw, minus backticks/newlines. */
    private fun stripBackticks(value: String): String =
        value.replace("`", "").replace('\n', ' ').replace('\r', ' ')
}
